"""Initial schema

Revision ID: 23d32298f553
Revises:
Create Date: 2026-06-19 07:49:39.432546

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "23d32298f553"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
